export default {
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',
  FETCH_USER: 'FETCH_USER',
  LOADING_SEARCH_PODCASTS: 'LOADING_SEARCH_PODCASTS',
  SEARCH_PODCASTS: 'SEARCH_PODCASTS',
  LOADING_CREATE_SUBSCRIPTION: 'LOADING_CREATE_SUBSCRIPTION',
  CREATE_SUBSCRIPTION: 'CREATE_SUBSCRIPTION',
  REMOVE_SUBSCRIPTION: 'REMOVE_SUBSCRIPTION',
  LOADING_FETCH_PODCAST: 'LOADING_FETCH_PODCAST',
  FETCH_PODCAST: 'FETCH_PODCAST',
  UPDATE_NOW_PLAYING: 'UPDATE_NOW_PLAYING',
  LOADING_FETCH_SUBSCRIPTIONS: 'LOADING_FETCH_SUBSCRIPTIONS',
  FETCH_SUBSCRIPTIONS: 'FETCH_SUBSCRIPTIONS',
  LOADING_RECENT_EPISODES: 'LOADING_RECENT_EPISODES',
  FETCH_RECENT_EPISODES: 'FETCH_RECENT_EPISODES'
}