export const playlistTypes = {
  PLAYLIST_UPDATING: 'PLAYLIST_UPDATING',
  PLAYLIST_CREATED: 'PLAYLIST_CREATED',
  PLAYLIST_REMOVED: 'PLAYLIST_REMOVED',
  PLAYLISTS_LOADING: 'PLAYLISTS_LOADING',
  PLAYLISTS_LOADED: 'PLAYLISTS_LOADED',
  CURRENT_TRACK_ENDED: 'CURRENT_TRACK_ENDED',
  UPDATE_NOW_PLAYING: 'UPDATE_NOW_PLAYING'
}