export const podcastTypes = {
  SEARCH_PODCASTS_LOADING: 'SEARCH_PODCASTS_LOADING',
  SEARCH_PODCASTS_LOADED: 'SEARCH_PODCASTS_LOADED',
  PODCAST_LOADING: 'PODCAST_LOADING',
  PODCAST_LOADED: 'PODCAST_LOADED',
  RECENT_EPISODES_LOADING: 'RECENT_EPISODES_LOADING',
  RECENT_EPISODES_LOADED: 'RECENT_EPISODES_LOADED'
}