export const subscriptionTypes = {
  SUBSCRIPTION_UPDATING: 'SUBSCRIPTION_UPDATING',
  SUBSCRIPTION_CREATED: 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_REMOVED: 'SUBSCRIPTION_REMOVED',
  SUBSCRIPTIONS_LOADING: 'SUBSCRIPTIONS_LOADING',
  SUBSCRIPTIONS_LOADED: 'SUBSCRIPTIONS_LOADED'
}